### ISSUE TITLE
[BUG] Newly loaded cog commands are not appearing in discord, despite cog showing being loaded

### ISSUE THREAD

**Issue by padraignix** [quantumlyconfused/qcadmin-discord-bot#7]
After successfully loading a cog, and showing that it is loaded. The commands are not present in discord, despite also triggering a sync command.

![Image](https://github.com/user-attachments/assets/a97279bd-b124-48cb-83bd-0195792ac5a1)

![Image](https://github.com/user-attachments/assets/19abfdda-f4f0-4753-a7c8-d60dff5bdce9)

```
2024-11-12 18:31:17,459:INFO:quantumly_confused_bot_log: Command sync initiated by .slurmsmackenzie...
2024-11-12 18:31:17,893:INFO:quantumly_confused_bot_log: Synced 5 commands.
2024-11-12 18:32:03,273:INFO:quantumly_confused_bot_log: Command sync initiated by padraignix...
2024-11-12 18:32:03,847:INFO:quantumly_confused_bot_log: Synced 5 commands.
```
![Image](https://github.com/user-attachments/assets/3b1f7f2f-ef03-4d45-8095-4958bfa12614)

**Comment by padraignix** [comment]
The fact that logs are showing "synced 5 commands" also indicates that the commands aren't being sent to discord, as those 5 commands the top level `/cog` and `/admin` commands.

**Comment by ropeadope62** [comment]
The cog is actually doing too much syncing, which could be cause for rate limiting and then nothing gets synced at all, but I dont think that is the issue. I spotted some inconsistency in my Interactions object creation by using lowercase i in Interaction: discord Interaction. This would be an interaction object in interactions.py NOT discord.py/interactions. 

**Fix**: make sure all command parameters expect 'Interaction: discord.Interaction' and when the interaction is called, await Interaction.response etc. 

**Syncing**: The bot sync is triggering in the event listener on_ready() and theres potential that if the bot has to reconnect to the discord api several times it will be resyncing and we are becoming rate limited. 

**Fix**: Move the await bot.tree.sync() to the main() function so it only syncs once when the bot starts.

**Comment by ropeadope62** [comment]
New class method for QCAdmin to take care of the class instance calls to bot.tree.sync: 

QCAdmin.sync_commands()

async def sync_commands(self):
        """Syncs the bot's commands with Discord on startup."""
        print("Bot Startup Command Sync initiated...")
        self.logger.info("Bot Startup Command Sync initiated...")
        try:
            synced = await self.bot.tree.sync()
            print(f"Command Sync Completed: Synced {len(synced)} commands.")
            self.logger.info(f"Command Sync Completed: Synced {len(synced)} commands.")
        except Exception as e:
            print(e)
            self.logger.error(f"Error syncing commands: {e}")

**Comment by ropeadope62** [comment]
PR Submitted to address issues

**Comment by ropeadope62** [comment]
Issue was resolved by kicking the bot and rejoining, clearing the registered app commands for the bot
